### ISSUE TITLE
Reimplement deep copy / merge features

### ISSUE THREAD

**Issue by ferrisoxide** [EventideSystems/tool_for_systemic_change#1031]
## Describe the task

Reintroduce the copy / merge features that used to be on the impact card grid page. These infrequently used features belong on the impact cards details page, under a "danger zone" section.

## Success Criteria

- [ ] ~~MUST allow account admin users to deep merge cards (see implementation in `ImpactCards::DeepMerge` service class)~~ Implemented as of #1050
- [ ] ~~MUST allow account admin users to deep copy cards (see implementation in `ImpactCards::DeepCopy` service class)~~ Not really all that useful. See DEV NOTES below.
- [ ] MUST reimplement old shallow copy as a service
- [ ] ~~MUST reimplement old shallow merge as a service~~ Implemented as of #1050
- [ ] ~~MUST allow account admin users to shallow merge cards (after reimplementing old code as a service class)~~ Implemented as of #1050
- [ ] MUST allow account admin users to shallow copy cards (after reimplementing old code as a service class)

**Comment by ferrisoxide** [comment]
### DEV NOTES

> ~~MUST allow account admin users to deep copy cards (see implementation in ImpactCards::DeepCopy service class)~~ 

Duplicating the entire comment history is less valuable that creating the structure of a new, empty card (i.e. initiatives and general settings). Won't implement, unless someone specifically asks for this feature.

**Comment by ferrisoxide** [comment]
### NOTES TO QA

The merge function was already introduced in #1050. Copy is now implemented only as a "shallow" feature, in that it will copy the structure of an existing card, but not the checklist item states or history.

The copy feature has been moved to the "Create Impact Card" page. When creating a new impact card the user will be prompted to select an existing impact card to copy the initiative structure from. 

Note:

- The option to select a source will not be available if the account you are using doesn't have any existing impact cards
- You can both select initiatives to import _and_ add a first initiative. 
- If the name of the first initiative you select exists in the source impact card, that initiative _will not_ be copied over (otherwise it would remove any subsystem tags, etc the user has set up 

@SishaMish This is on staging and ready for QA.

**Comment by SishaMish** [comment]
@ferrisoxide QA'd and passed :+1:
